{{- if .Values.deployments.service.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.deployments.service.name }}-hpa
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
  labels:
    app.kubernetes.io/name: {{ include "tranzrmoves.name" . }}-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: service
    {{- include "tranzrmoves.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deployments.service.name }}
  minReplicas: {{ .Values.deployments.service.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.deployments.service.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.deployments.service.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.deployments.service.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.deployments.service.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.deployments.service.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }} 