{{- if .Values.deployments.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.backend.name }}
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
  labels:
    app.kubernetes.io/name: {{ include "tranzrmoves.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    {{- include "tranzrmoves.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.backend.type }}
  ports:
    - port: {{ .Values.services.backend.port }}
      targetPort: {{ .Values.services.backend.targetPort }}
      protocol: {{ .Values.services.backend.protocol }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "tranzrmoves.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
{{- end }} 