# Default values for tranzrmoves.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
global:
  defaultStorageClass: "synology-iscsi-delete"

# Namespace override
namespaceOverride: "tranzr-moves"

# Deployments configuration
deployments:
  gateway:
    name: tranzr-gateway
    enabled: true
    replicaCount: 1
    image:
      repository: ghcr.io/tranz-r/api-gateway
      pullPolicy: IfNotPresent
      tag: "0.17.0"
    
    # Container port configuration
    containerPort: 8080
    
    # Regular environment variables (plain values)
    env:
      - name: LOG_LEVEL
        value: "info"
      - name: PORT
        value: "8080"
      - name: NODE_ENV
        value: "production"
    
    # Environment variables from External Secrets
    envFromSecrets:
      - name: SUPER_BASE_JWT_SECRET_KEY
        secretKey: supabase-jwt-secret-key
      - name: SUPER_BASE_PROJECT_ID
        secretKey: supabase-project-id
    
    # Resource configuration
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    
    # Probes configuration
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
    
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 15
      periodSeconds: 15
    
    # Autoscaling configuration
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

  backend:
    name: tranzr-service
    enabled: true
    replicaCount: 1
    image:
      repository: ghcr.io/tranz-r/tranzr-moves-services
      pullPolicy: IfNotPresent
      tag: "0.10.0"
    
    # Container port configuration
    containerPort: 8080
    
    # Regular environment variables (plain values)
    env:
      - name: LOG_LEVEL
        value: "debug"
      - name: PORT
        value: "8080"
      - name: NODE_ENV
        value: "production"
      - name: CACHE_TTL
        value: "300"
      - name: AWS_SES_SMTP_PORT
        value: "587"
      - name: FROM_EMAIL
        value: "bookings@tranzrmoves.com"
      - name: FROM_NAME
        value: "Tranzr Moves"
      - name: AWS_DEFAULT_REGION
        value: "eu-west-2"
      - name: AWS_REGION
        value: "eu-west-2"
      - name: MAPBOX_BASE_URL
        value: "https://api.mapbox.com"
    
    # Environment variables from External Secrets
    envFromSecrets:
      - name: STRIPE_API_KEY
        secretKey: tranzr-stripe-api-key
      - name: SUPABASE_URL
        secretKey: supabase-url
      - name: SUPABASE_KEY
        secretKey: supabase-key
      - name: ADDRESS_API_KEY
        secretKey: getaddressio-address-api-key
      - name: ADDRESS_ADMINISTRATION_KEY
        secretKey: getaddressio-address-administration-key
      - name: TRANZR_STRIPE_WEBHOOK_SIGNING_SECRET
        secretKey: tranzr-stripe-webhook-signing-secret
      - name: AWS_SES_SMTP_HOST
        secretKey: aws-ses-smtp-host
      - name: AWS_SES_SMTP_USERNAME
        secretKey: aws-ses-smtp-username
      - name: AWS_SES_SMTP_PASSWORD
        secretKey: aws-ses-smtp-password
      - name: AWS_ACCESS_KEY_ID
        secretKey: aws-access-key-id
      - name: AWS_SECRET_ACCESS_KEY
        secretKey: aws-secret-access-key
      - name: ConnectionStrings__TranzrMovesDatabaseConnection
        secretKey: tranzr-postgres-connection-string
      - name: MAPBOX_TOKEN
        secretKey: mapbox-token
      - name: AZURE_STORAGE_CONNECTION_STRING
        secretKey: tranzr-azure-storage-connection-string
    
    # Resource configuration
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    # Probes configuration
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
    
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
    
    # Autoscaling configuration
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 15
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

# Image pull secrets configuration
imagePullSecrets:
  - name: github-registry-secret

# Service accounts configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod configuration
podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Services configuration
services:
  gateway:
    name: tranzr-gateway
    type: ClusterIP
    port: 80
    targetPort: 8080
    protocol: TCP
  
  backend:
    name: tranzr-service
    type: ClusterIP
    port: 80
    targetPort: 8080
    protocol: TCP

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: tranzr-gw.labgrid.net
      paths:
        - path: /
          pathType: Prefix
          serviceName: tranzr-gateway
          servicePort: 80
  tls:
    - secretName: tranzr-gateway-tls
      hosts:
        - tranzr-gw.labgrid.net

# Consolidated External Secrets configuration
externalSecrets:
  enabled: true
  name: tranzrmoves-secrets
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-cluster-store
    kind: ClusterSecretStore
  
  # GitHub registry configuration
  githubRegistry:
    usernameKey: github-registry-username
    tokenKey: github-registry-token
  
  # Create separate image pull secret (dockerconfigjson type)
  createImagePullSecret: true
  
  # Application secrets - add all your application secrets here
  # Simple direct mapping from Azure Key Vault to Kubernetes secret
  applicationSecrets:
    # Gateway secrets - currently none configured
    - secretKey: supabase-jwt-secret-key
      description: "Supabase JWT signing secret"
      remoteRef:
        key: supabase-jwt-secret-key
    - secretKey: supabase-project-id
      description: "Supabase project ID"
      remoteRef:
        key: supabase-project-id
    
    # Backend secrets
    - secretKey: tranzr-stripe-api-key
      description: "Stripe API key for payment processing"
      remoteRef:
        key: tranzr-stripe-api-key
    - secretKey: supabase-url
      description: "Supabase database URL"
      remoteRef:
        key: supabase-url
    - secretKey: supabase-key
      description: "Supabase service key"
      remoteRef:
        key: supabase-key
    - secretKey: getaddressio-address-api-key
      description: "GetAddress.io API key"
      remoteRef:
        key: getaddressio-address-api-key
    - secretKey: getaddressio-address-administration-key
      description: "GetAddress.io administration key"
      remoteRef:
        key: getaddressio-address-administration-key
    - secretKey: tranzr-stripe-webhook-signing-secret
      description: "Stripe webhook signing secret"
      remoteRef:
        key: tranzr-stripe-webhook-signing-secret
    - secretKey: aws-ses-smtp-host
      description: "AWS SES SMTP host"
      remoteRef:
        key: aws-ses-smtp-host
    - secretKey: aws-ses-smtp-username
      description: "AWS SES SMTP username"
      remoteRef:
        key: aws-ses-smtp-username
    - secretKey: aws-ses-smtp-password
      description: "AWS SES SMTP password"
      remoteRef:
        key: aws-ses-smtp-password
    - secretKey: aws-access-key-id
      description: "AWS access key ID"
      remoteRef:
        key: aws-access-key-id
    - secretKey: aws-secret-access-key
      description: "AWS secret access key"
      remoteRef:
        key: aws-secret-access-key
    - secretKey: mapbox-token
      description: "Mapbox token"
      remoteRef:
        key: mapbox-token
    - secretKey: tranzr-azure-storage-connection-string
      description: "Azure storage connection string"
      remoteRef:
        key: tranzr-azure-storage-connection-string
    
    # Database secrets
    - secretKey: tranzr-postgres-connection-string
      description: "PostgreSQL database connection string"
      remoteRef:
        key: tranzr-postgres-connection-string

# Node selector, tolerations, and affinity
nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - tranzrmoves
          topologyKey: kubernetes.io/hostname

# Jobs configuration
jobs:
  dbMigration:
    enabled: true
    backoffLimit: 3
    image:
      repository: ghcr.io/tranz-r/tranzr-moves-db-migrator
      pullPolicy: IfNotPresent
      tag: "0.10.0"  # Should match the backend service version
    restartPolicy: Never
    database:
      port: 5432
    

    
    # Init container resources
    initContainer:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    
    # Main container resources
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    # Regular environment variables (plain values)
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: "Production"
      - name: LOG_LEVEL
        value: "Information"
    
    # Environment variables from External Secrets
    envFromSecrets:
      - name: DB_CONNECTION_STRING
        secretKey: tranzr-postgres-connection-string
      - name: TRANZR_SUPABASE_PROJECT_ID
        secretKey: tranzr-supabase-project-id

# Additional volumes and volume mounts
volumes: []
volumeMounts: []
