# Default values for tranzrmoves.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
global:
  defaultStorageClass: "synology-iscsi-delete"

# Namespace override
namespaceOverride: "tranzr-moves"

# Deployments configuration
deployments:
  gateway:
    name: tranzr-gateway
    enabled: true
    replicaCount: 2
    image:
      repository: ghcr.io/tranz-r/api-gateway
      pullPolicy: IfNotPresent
      tag: "0.14.1"
    
    # Container port configuration
    containerPort: 8080
    
    # Regular environment variables (plain values)
    env:
      - name: LOG_LEVEL
        value: "info"
      - name: PORT
        value: "8080"
      - name: NODE_ENV
        value: "production"
    
    # Environment variables from External Secrets
    envFromSecrets: []
      # - name: JWT_SECRET
      #   secretKey: gateway-jwt-secret
      # - name: API_KEY
      #   secretKey: gateway-api-key
      # - name: DATABASE_URL
      #   secretKey: gateway-database-url
    
    # Resource configuration
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    
    # Probes configuration
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
    
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 15
      periodSeconds: 15
    
    # Autoscaling configuration
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

  backend:
    name: tranzr-service
    enabled: true
    replicaCount: 2
    image:
      repository: ghcr.io/tranz-r/tranzr-moves-services
      pullPolicy: IfNotPresent
      tag: "0.1.6"
    
    # Container port configuration
    containerPort: 8080
    
    # Regular environment variables (plain values)
    env:
      - name: LOG_LEVEL
        value: "debug"
      - name: PORT
        value: "8080"
      - name: NODE_ENV
        value: "production"
      - name: CACHE_TTL
        value: "300"
    
    # Environment variables from External Secrets
    envFromSecrets:
      - name: STRIPE_API_KEY
        secretKey: tranzr-stripe-api-key
      - name: SUPABASE_URL
        secretKey: supabase-url
      - name: SUPABASE_KEY
        secretKey: supabase-key
    
    # Resource configuration
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    # Probes configuration
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
    
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
    
    # Autoscaling configuration
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 15
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

# Image pull secrets configuration
imagePullSecrets:
  - name: github-registry-secret

# Service accounts configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod configuration
podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Services configuration
services:
  gateway:
    name: tranzr-gateway
    type: ClusterIP
    port: 80
    targetPort: 8080
    protocol: TCP
  
  backend:
    name: tranzr-service
    type: ClusterIP
    port: 80
    targetPort: 8080
    protocol: TCP

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: tranzr-gw.labgrid.net
      paths:
        - path: /
          pathType: Prefix
          serviceName: tranzr-gateway
          servicePort: 80
  tls:
    - secretName: tranzr-gateway-tls
      hosts:
        - tranzr-gw.labgrid.net

# Consolidated External Secrets configuration
externalSecrets:
  enabled: true
  name: tranzrmoves-secrets
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-cluster-store
    kind: ClusterSecretStore
  
  # GitHub registry configuration
  githubRegistry:
    usernameKey: github-registry-username
    tokenKey: github-registry-token
  
  # Create separate image pull secret (dockerconfigjson type)
  createImagePullSecret: true
  
  # Application secrets - add all your application secrets here
  # Simple direct mapping from Azure Key Vault to Kubernetes secret
  applicationSecrets:
    # Gateway secrets - currently none configured
    # - secretKey: gateway-jwt-secret
    #   description: "Gateway JWT signing secret"
    #   remoteRef:
    #     key: tranzr-gateway-jwt-secret
    # - secretKey: gateway-api-key
    #   description: "Gateway API key"
    #   remoteRef:
    #     key: tranzr-gateway-api-key
    
    # Backend secrets
    - secretKey: tranzr-stripe-api-key
      description: "Stripe API key for payment processing"
      remoteRef:
        key: tranzr-stripe-api-key
    - secretKey: supabase-url
      description: "Supabase database URL"
      remoteRef:
        key: supabase-url
    - secretKey: supabase-key
      description: "Supabase service key"
      remoteRef:
        key: supabase-key

# Node selector, tolerations, and affinity
nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - tranzrmoves
          topologyKey: kubernetes.io/hostname

# Additional volumes and volume mounts
volumes: []
volumeMounts: []
