{{- if .Values.chatwoot.secretStore.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.chatwoot.secretStore.name }}-role
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
  labels:
    app.kubernetes.io/component: {{ printf "%s-rbac" .Values.chatwoot.secretStore.name | quote }}
    app.kubernetes.io/name: {{ include "tranzrmoves.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    {{- include "tranzrmoves.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.chatwoot.secretStore.name }}-binding
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
  labels:
    app.kubernetes.io/component: {{ printf "%s-rbac" .Values.chatwoot.secretStore.name | quote }}
    app.kubernetes.io/name: {{ include "tranzrmoves.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    {{- include "tranzrmoves.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.chatwoot.secretStore.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "tranzrmoves.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
{{- end }}
