{{- if .Values.chatwoot.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.chatwoot.secretStore.name }}
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
  labels:
    app.kubernetes.io/component: {{ .Values.chatwoot.secretStore.name | quote }}
    app.kubernetes.io/name: {{ include "tranzrmoves.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    {{- include "tranzrmoves.labels" . | nindent 4 }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
{{- end }}
