{{- if .Values.externalSecrets.createImagePullSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ (index .Values.imagePullSecrets 0).name }}
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
  labels:
    app.kubernetes.io/component: {{ (index .Values.imagePullSecrets 0).name | quote }}
    app.kubernetes.io/name: {{ include "tranzrmoves.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    {{- include "tranzrmoves.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ `{{ .github_registry_username }}` }}",
                "password": "{{ `{{ .github_registry_token }}` }}",
                "auth": "{{ `{{ printf "%s:%s" .github_registry_username .github_registry_token | b64enc }}` }}"
              }
            }
          }
  data:
    - secretKey: github_registry_username
      remoteRef:
        key: {{ .Values.externalSecrets.githubRegistry.usernameKey }}
    - secretKey: github_registry_token
      remoteRef:
        key: {{ .Values.externalSecrets.githubRegistry.tokenKey }}
{{- end }} 