{{- if and .Values.externalSecrets.enabled .Values.platformMessaging.enabled }}
{{- $redisEndpoint := printf "%s:%s" .Values.platformMessaging.redis.host (.Values.platformMessaging.redis.port | toString) }}
{{- $rabbitEndpoint := printf "%s:%s" .Values.platformMessaging.rabbitmq.host (.Values.platformMessaging.rabbitmq.port | toString) }}
{{- $rabbitUser := .Values.platformMessaging.rabbitmq.username }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}-platform-messaging
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
  labels:
    app.kubernetes.io/component: platform-messaging
    app.kubernetes.io/name: {{ include "tranzrmoves.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    {{- include "tranzrmoves.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-8"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.name }}
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        tranzr-redis-connection-string: {{ print "{{ .redis_password | printf \"" $redisEndpoint ",password=%s\" }}" | quote }}
        tranzr-rabbitmq-connection-string: {{ print "{{ .rabbitmq_password | printf \"amqp://" $rabbitUser ":%s@" $rabbitEndpoint "\" }}" | quote }}
  data:
    - secretKey: redis_password
      remoteRef:
        key: platform-redis-password
    - secretKey: rabbitmq_password
      remoteRef:
        key: platform-rabbitmq-password
{{- end }}
