{{- if .Values.deployments.service.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.service.name }}
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
  labels:
    app.kubernetes.io/name: {{ include "tranzrmoves.name" . }}-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: service
    {{- include "tranzrmoves.labels" . | nindent 4 }}
spec:
  {{- if not .Values.deployments.service.autoscaling.enabled }}
  replicas: {{ .Values.deployments.service.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tranzrmoves.name" . }}-service
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: service
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "tranzrmoves.name" . }}-service
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: service
        {{- include "tranzrmoves.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tranzrmoves.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.deployments.service.name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.deployments.service.image.repository }}:{{ .Values.deployments.service.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployments.service.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployments.service.containerPort }}
              protocol: TCP
          {{- if .Values.externalSecrets.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecrets.name }}
          {{- end }}
          {{- if .Values.deployments.service.environmentVariables }}
          env:
            {{- range .Values.deployments.service.environmentVariables }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.externalSecrets.name }}
                  key: {{ .secretKey }}
            {{- end }}
          {{- end }}
          {{- with .Values.deployments.service.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployments.service.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployments.service.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 