{{- if .Values.deployments.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.gateway.name }}
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
  labels:
    app.kubernetes.io/name: {{ include "tranzrmoves.name" . }}-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
    {{- include "tranzrmoves.labels" . | nindent 4 }}
spec:
  {{- if not .Values.deployments.gateway.autoscaling.enabled }}
  replicas: {{ .Values.deployments.gateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tranzrmoves.name" . }}-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "tranzrmoves.name" . }}-gateway
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: gateway
        helm.sh/chart: {{ include "tranzrmoves.chart" . }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tranzrmoves.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.deployments.gateway.name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.deployments.gateway.image.repository }}:{{ .Values.deployments.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployments.gateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployments.gateway.containerPort }}
              protocol: TCP
          {{- if or .Values.deployments.gateway.env .Values.deployments.gateway.envFromSecrets }}
          env:
            {{- range .Values.deployments.gateway.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.deployments.gateway.envFromSecrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.externalSecrets.name }}
                  key: {{ .secretKey }}
            {{- end }}
          {{- end }}
          {{- with .Values.deployments.gateway.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployments.gateway.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployments.gateway.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 